CREATE TABLE USUARIO (
	ID SERIAL PRIMARY KEY,
	NICK VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE DOUTOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CRM VARCHAR(50) NOT NULL,
	ESPECIALIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE PACIENTE (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	IDADE VARCHAR(50) NOT NULL,
	CPF VARCHAR(50) NOT NULL
);

CREATE TABLE CONSULTA (
	ID SERIAL PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	ID_DOUTOR INT NOT NULL,
	ID_PACIENTE INT NOT NULL,
	CONSTRAINT "USUARIO_FK" FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
	CONSTRAINT "DOUTOR_FK" FOREIGN KEY (ID_DOUTOR) REFERENCES DOUTOR (ID),
	CONSTRAINT "PACIENTE_FK" FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID)
);